module(load="imudp")
module(load="imtcp")

input(type="imudp" port="1514")
input(type="imtcp" port="1514")

# Use the device's hostname/IP to split into per-device files
template(name="PerHostLog" type="string" string="/var/log/network/%HOSTNAME%.log")

if $fromhost-ip != '127.0.0.1' then {
    action(type="omfile" dynaFile="PerHostLog")
}

stop